name: Keep Supabase Alive Pdf a Excel

on:
  schedule:
    # Se ejecuta a las 00:00 cada 5 d√≠as
    - cron: '0 0 */5 * *'
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  ping_db:
    runs-on: ubuntu-latest
    steps:
      - name: Install psql
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Ping Supabase Database
        env:
          DB_URL: ${{ secrets.SUPABASE_DB_URL_PDF_EXCEL }}
        run: |
          psql "$DB_URL" -c "SELECT 1;"
